version: '3'

services:
  ftp-server:
    build: .
    ports:
      - "21:21"
      - "1024-30000:1024-30000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FTP_PORT=21
      - PASV_URL=${PUBLIC_IP}  # Set this to your VPS's public IP
      - PASV_MIN=1024
      - PASV_MAX=30000
      - DB_USER=${DB_USER:-finale}
      - DB_HOST=${DB_HOST:-192.3.166.251}
      - DB_NAME=${DB_NAME:-finaledb}
      - DB_PASSWORD=${DB_PASSWORD:-Inventory22025}
      - DB_PORT=${DB_PORT:-5435}
    restart: always
    network_mode: "host"  # Use host network mode for better connectivity
